name: CI API

on:
  pull_request:
    branches:
      - main
    paths:
      - 'MAVI.Connect/**'
      - '.github/workflows/**'

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  validate-dotnet:
    name: Validate .NET API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore and Build
        run: dotnet build --configuration Release
