name: CI – Build .NET Backend

on:
  push:
    paths-ignore:
      - 'MAVI.Client/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'MAVI.Client/**'
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build .NET backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: MAVI.API/Dockerfile
          push: false
          tags: mavi-backend:test
