name: CI – Build Angular Client

on:
  push:
    paths:
      - 'MAVI.Client/**'
    branches:
      - main
  pull_request:
    paths:
      - 'MAVI.Client/**'
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Angular client Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: MAVI.Client/Dockerfile
          push: false
          tags: mavi-client:test
