name: Client - CD

on:
  push:
    branches:
      - main
    paths:
      - 'MAVIConnect/MAVI.Client/**'
      - '.github/workflows/client-cd.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd MAVI.Client
          npm install

      - name: Build Angular app
        run: |
          cd MAVI.Client
          npm run build -- --configuration production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "MAVI.Client"
          output_location: "dist/mavi.client/browser"
